---
# tasks file for lighthouse-role
- name: Install EPEL repo
  become: true
  ansible.builtin.yum:
    name: epel-release
    state: present
- name: Install nginx packages
  become: true
  ansible.builtin.yum:
    name: nginx
- name: Deploy config
  become: true
  ansible.builtin.template:
    src: nginx.j2
    dest: /etc/nginx/nginx.conf
    mode: "0644"
  notify: Nginx restart service
- name: Install git
  become: true
  ansible.builtin.yum:
    name: git
    state: present
- name: Get lighthouse from git
  ansible.builtin.git:
    repo: "{{ source }}"
    version: master
    dest: "{{ dir }}"
  become: true
- name: Remove default nginx config
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: true
- name: Create web config
  become: true
  ansible.builtin.template:
    src: lighthouse.j2
    dest: /etc/nginx/conf.d/default.conf
    mode: "0644"
  notify: Nginx restart service
  tags: 08-ansible-03-yandex
